# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-17 13:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('pages', models.PositiveIntegerField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('published', models.DateField(blank=True, null=True)),
                ('visible', models.NullBooleanField(default=False)),
                ('type_book', models.PositiveIntegerField(choices=[(1, 'e-Book'), (2, 'Paper book')])),
            ],
            options={
                'verbose_name': 'Livro',
                'verbose_name_plural': 'Livros',
                'ordering': ('-updated',),
            },
        ),
    ]
