# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-02 13:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20170222_1941'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useractivation',
            name='user',
        ),
        migrations.DeleteModel(
            name='UserActivation',
        ),
    ]
